# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Setup GitHub NuGet
        run: dotnet nuget add source --username Jarak-Jakar --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/Jarak-Jakar/index.json"
      - name: Restore dependencies
        run: dotnet restore
      - name: Output NuGet locations
        run: echo "NUGET_GLOBAL_LOCATION=$(dotnet nuget locals --list all | grep -i 'global-packages' | head -1)" >> $GITHUB_ENV
      - name: Extract cache location
        run: echo "NUGET_GLOBAL_LOCATION_TRIMMED=${NUGET_GLOBAL_LOCATION:17}" >> $GITHUB_ENV
      - name: Test NuGet location lookup
        run: |
          echo $NUGET_GLOBAL_LOCATION
          echo $NUGET_GLOBAL_LOCATION_TRIMMED
      - name: List NuGet cache contents to see where lib is stored
        run: ls --all --recursive $NUGET_GLOBAL_LOCATION_TRIMMED
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build --verbosity normal
      - name: Try to run program to prove it works
        run: dotnet run --project ./prog/prog.fsproj

