name: Upload dotnet package

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x' # SDK Version to use.
          source-url: https://nuget.pkg.github.com/Jarak-Jakar/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - run: dotnet build --configuration Release ./lib/lib.fsproj
      - name: Create the package
        run: dotnet pack --configuration Release ./lib/lib.fsproj
      - name: Publish the package to GPR
        run: dotnet nuget push ./lib/bin/Release/*.nupkg
